import type {
	IDataObject,
	IExecuteFunctions,
	INodeExecutionData,
	INodeProperties,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { WIDGET_MAP_TICKER_ADD_OR_UPDATE_AGENT_DETAILS_LINK } from '../../helpers/linkConstants';
import { getRequiredScopeForOperation } from '../../helpers/scopeRegistry';
import { checkRequiredScope } from '../../helpers/utils';
import { zohoCliqApiRequest } from '../../transport';
import {
	extractWidgetMapTickerRecoverableContext,
	extractTickerRequestContext,
	pushWidgetMapTickerRecoverableError,
	resolveWidgetMapTickerEnhancedOutput,
	TICKER_COLORS,
	validateTickerBody,
	validateTickerId,
} from './common';
import { applyDisplayOptions } from '../common.descriptions';

const requiredScope = getRequiredScopeForOperation('widgetMapTicker', 'addOrUpdateTicker');

const properties: INodeProperties[] = [
	{
		displayName: 'Input Mode',
		name: 'inputMode',
		type: 'options',
		options: [
			{ name: 'Using Fields Below', value: 'structured' },
			{ name: 'Using JSON', value: 'raw' },
		],
		default: 'structured',
		description:
			'Choose Using Fields Below for guided ticker entry, or Using JSON for advanced payloads that already match the API body schema',
	},
	{
		displayName: 'Map Is Custom Extension',
		name: 'mapIsCustomExtension',
		type: 'boolean',
		default: false,
		description:
			'Whether the widget map belongs to a custom extension. When enabled, this operation uses the extension endpoint and sends appkey as a query parameter.',
	},
	{
		displayName: 'Widget ID',
		name: 'widgetId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				mapIsCustomExtension: [false],
			},
		},
		placeholder: 'e.g. WD_1234567890',
		description:
			'Unique widget ID from Zoho Cliq widget settings. Required only for the internal widget API endpoint /widgets/{WIDGET_ID}/maps/{MAP_ID}.',
	},
	{
		displayName: 'Map ID',
		name: 'mapId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. MAP_1234567890',
		description:
			'Unique map ID for the target map. Internal widgets use /widgets/{WIDGET_ID}/maps/{MAP_ID}; extensions use /extensions/widgets/maps/{MAP_ID}.',
	},
	{
		displayName: 'App Key',
		name: 'appKey',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				mapIsCustomExtension: [true],
			},
		},
		placeholder: 'e.g. 1000.xxxxxx.yyyyyy',
		description:
			'Extension app key. In Cliq navigate to My Profile (Avatar Top Right) > Bots & Tools > My Extensions (Left Sidebar) > Select your Extension > Connectors (Tab), then copy either Sandbox App Key or Marketplace App Key depending on your deployment.',
	},
	{
		displayName: 'Tickers',
		name: 'tickerEntries',
		type: 'fixedCollection',
		placeholder: 'Add Ticker Object',
		typeOptions: {
			multipleValues: true,
			sortable: true,
		},
		default: {
			ticker: [],
		},
		required: true,
		displayOptions: {
			show: {
				inputMode: ['structured'],
			},
		},
		description:
			'Add one or more ticker entries. Each entry becomes tickers.&lt;tickerId&gt; in the API payload.',
		options: [
			{
				name: 'ticker',
				displayName: 'Ticker',
				values: [
					{
						displayName: 'Color',
						name: 'color',
						type: 'options',
						default: '',
						options: [
							{
								name: 'None',
								value: '',
							},
							...TICKER_COLORS.map((color) => ({
								name: `${color.charAt(0).toUpperCase()}${color.slice(1)}`,
								value: color,
							})),
						],
						description: `Optional ticker color. Allowed values: ${TICKER_COLORS.join(', ')}.`,
					},
					{
						displayName: 'Info',
						name: 'info',
						type: 'string',
						default: '',
						description: 'Optional additional info (maximum 30 characters)',
					},
					{
						displayName: 'Last Modified Time',
						name: 'lastModifiedTime',
						type: 'number',
						default: 0,
						required: true,
						description:
							'Epoch timestamp in milliseconds for when this ticker was last updated (positive whole number)',
					},
					{
						displayName: 'Latitude',
						name: 'latitude',
						type: 'number',
						default: 0,
						required: true,
						description: 'Latitude coordinate between -90 and 90',
					},
					{
						displayName: 'Longitude',
						name: 'longitude',
						type: 'number',
						default: 0,
						required: true,
						description: 'Longitude coordinate between -180 and 180',
					},
					{
						displayName: 'Ticker ID',
						name: 'tickerId',
						type: 'string',
						default: '',
						required: true,
						placeholder: 'e.g. chennai',
						description:
							'Identifier for this ticker entry, such as a city or asset ID. This value is used as the ticker key in the API payload and is not auto-generated by Cliq. Allowed: letters, numbers, hyphen, underscore.',
					},
					{
						displayName: 'Ticker Title',
						name: 'title',
						type: 'string',
						default: '',
						required: true,
						description:
							'Human-readable ticker title (maximum 20 characters). Example: TN 07 AL 9916.',
					},
					{
						displayName: 'Ticker Type',
						name: 'type',
						type: 'options',
						default: 'person',
						options: [
							{
								name: 'Bicycle',
								value: 'bicycle',
							},
							{
								name: 'Bus',
								value: 'bus',
							},
							{
								name: 'Car',
								value: 'car',
							},
							{
								name: 'Home',
								value: 'home',
							},
							{
								name: 'Motorcycle',
								value: 'motorcycle',
							},
							{
								name: 'Office',
								value: 'office',
							},
							{
								name: 'Person',
								value: 'person',
							},
							{
								name: 'Plane',
								value: 'plane',
							},
							{
								name: 'Van',
								value: 'van',
							},
						],
						description: 'Ticker category as defined by the Zoho Cliq API schema enum',
					},
					{
						displayName: 'Tracking Destination',
						name: 'addDestination',
						type: 'boolean',
						default: false,
						description:
							"Whether to include a destination location for this ticker. When enabled, the map draws a route from the ticker's current position to the destination, enabling live route tracking.",
					},
					{
						displayName: 'Tracking Destination — Latitude',
						name: 'destinationLatitude',
						type: 'number',
						default: undefined,
						typeOptions: {
							minValue: -90,
							maxValue: 90,
						},
						displayOptions: {
							show: {
								addDestination: [true],
							},
						},
						description:
							"Latitude of the destination endpoint for route tracking (-90 to 90). This is the route target location, not the ticker's current position.",
					},
					{
						displayName: 'Tracking Destination — Longitude',
						name: 'destinationLongitude',
						type: 'number',
						default: undefined,
						typeOptions: {
							minValue: -180,
							maxValue: 180,
						},
						displayOptions: {
							show: {
								addDestination: [true],
							},
						},
						description:
							"Longitude of the destination endpoint for route tracking (-180 to 180). This is the route target location, not the ticker's current position.",
					},
				],
			},
		],
	},
	{
		displayName: 'Ticker Payload (JSON)',
		name: 'tickerPayload',
		type: 'json',
		default: '{"tickers":{}}',
		required: true,
		displayOptions: {
			show: {
				inputMode: ['raw'],
			},
		},
		description:
			'Raw request body for add/update ticker. Must be an object with a non-empty tickers object. Optional color values are green, red, or yellow. Example: {"tickers":{"chennai":{"title":"TN 07 AL 9916","type":"van","color":"green","last_modified_time":1721329461000,"latitude":12.84567,"longitude":80.06092,"info":"Towards Zoho Corporation"}}}',
	},
	{
		displayName: 'Include Enhanced Output',
		name: 'includeEnhancedOutput',
		type: 'boolean',
		default: true,
		noDataExpression: true,
		description:
			"Whether to return workflow-friendly success metadata with widget/map context and explicit ticker IDs. Disable to return Cliq's standard ticker response.",
	},
	{
		displayName: `Add or Update Ticker Docs: <a href="https://www.zoho.com/cliq/help/restapi/v2/#add_ticker" target="_blank" rel="noopener noreferrer">Open Zoho REST API Reference</a> REQUIRED SCOPES: <code>${requiredScope}</code>`,
		name: 'addOrUpdateTickerDocsNotice',
		type: 'notice',
		default: '',
	},
	{
		displayName:
			'Extension Guidance: <a href="https://www.zoho.com/cliq/help/platform/build-cliq-extensions.html" target="_blank" rel="noopener noreferrer">Build Zoho Cliq Extensions</a>',
		name: 'addOrUpdateTickerExtensionDocsNotice',
		type: 'notice',
		default: '',
	},
	{
		displayName: `Zoho Cliq Widget Map Tickers/Add or Update Ticker as AI Tool Setup Guide: <a href="${WIDGET_MAP_TICKER_ADD_OR_UPDATE_AGENT_DETAILS_LINK}" target="_blank" rel="noopener noreferrer">Open Tool Setup Guide</a>`,
		name: 'addOrUpdateTickerAiToolGuideNotice',
		type: 'notice',
		default: '',
	},
];

const displayOptions = {
	show: {
		resource: ['widgetMapTicker'],
		operation: ['addOrUpdateTicker'],
	},
};

export const description: INodeProperties[] = applyDisplayOptions(properties, displayOptions);

function buildStructuredTickerPayload(
	context: IExecuteFunctions,
	itemIndex: number,
	rawEntries: IDataObject,
): IDataObject {
	const rawTickerEntries = rawEntries.ticker;
	const entries = Array.isArray(rawTickerEntries)
		? rawTickerEntries.filter((entry) => entry && typeof entry === 'object')
		: [];

	if (entries.length === 0) {
		return validateTickerBody(context, { tickers: {} }, itemIndex, 'Ticker Payload');
	}

	const tickers: IDataObject = {};
	for (const entry of entries) {
		const tickerId = validateTickerId(context, String(entry.tickerId ?? ''), itemIndex);
		const tickerPayload: IDataObject = {
			title: entry.title,
			type: entry.type,
			last_modified_time: entry.lastModifiedTime,
			latitude: entry.latitude,
			longitude: entry.longitude,
		};
		if (entry.info !== undefined && String(entry.info).trim()) {
			tickerPayload.info = String(entry.info).trim();
		}
		if (entry.color !== undefined && String(entry.color).trim()) {
			tickerPayload.color = String(entry.color).trim();
		}
		if (entry.addDestination === true) {
			const destLat = Number(entry.destinationLatitude);
			const destLng = Number(entry.destinationLongitude);
			if (Number.isFinite(destLat) && Number.isFinite(destLng)) {
				tickerPayload.destination = {
					latitude: destLat,
					longitude: destLng,
				};
			}
		}
		tickers[tickerId] = tickerPayload;
	}

	return validateTickerBody(context, { tickers }, itemIndex, 'Ticker Payload');
}

function assertTickerAddOrUpdateSucceeded(
	context: IExecuteFunctions,
	itemIndex: number,
	response: IDataObject,
): void {
	if (response.status !== false) {
		return;
	}

	const responseDetail =
		typeof response.message === 'string' && response.message.trim()
			? response.message.trim()
			: typeof response.error === 'string' && response.error.trim()
				? response.error.trim()
				: JSON.stringify(response);

	throw new NodeOperationError(
		context.getNode(),
		`Zoho Cliq reported ticker add/update was not applied (status=false). Response: ${responseDetail}`,
		{ itemIndex },
	);
}

export async function execute(
	this: IExecuteFunctions,
	items: INodeExecutionData[],
	grantedScopes: string,
): Promise<INodeExecutionData[]> {
	const returnData: INodeExecutionData[] = [];

	for (let i = 0; i < items.length; i++) {
		let sanitizedMapId: string | undefined;
		let sanitizedWidgetId: string | undefined;
		let tickerIds: string[] = [];
		let requestedAppKey: string | undefined;

		try {
			checkRequiredScope(this, grantedScopes, requiredScope, i);
			const recoverableContext = extractWidgetMapTickerRecoverableContext(this, i, {
				operation: 'addOrUpdateTicker',
				structuredEntriesFieldName: 'tickerEntries',
				structuredEntriesDefault: { ticker: [] },
				rawPayloadFieldName: 'tickerPayload',
				payloadPath: 'Ticker Payload',
				supportExtensionEndpoint: true,
			});
			sanitizedMapId =
				typeof recoverableContext.map_id === 'string' ? recoverableContext.map_id : undefined;
			sanitizedWidgetId =
				typeof recoverableContext.widget_id === 'string' ? recoverableContext.widget_id : undefined;
			tickerIds = Array.isArray(recoverableContext.ticker_ids)
				? [...(recoverableContext.ticker_ids as string[])]
				: [];
			requestedAppKey =
				typeof recoverableContext.appkey === 'string' ? recoverableContext.appkey : undefined;

			const {
				endpoint,
				body,
				qs,
				sanitizedMapId: mapId,
				sanitizedWidgetId: widgetId,
			} = extractTickerRequestContext(this, i, {
				structuredEntriesFieldName: 'tickerEntries',
				structuredEntriesDefault: { ticker: [] },
				rawPayloadFieldName: 'tickerPayload',
				payloadPath: 'Ticker Payload',
				buildStructuredPayload: buildStructuredTickerPayload,
				validatePayload: validateTickerBody,
				supportExtensionEndpoint: true,
			});
			sanitizedMapId = mapId;
			sanitizedWidgetId = widgetId;
			tickerIds = Object.keys(body.tickers as IDataObject);
			requestedAppKey = typeof qs.appkey === 'string' ? qs.appkey : requestedAppKey;

			const response = await zohoCliqApiRequest.call(this, 'PUT', endpoint, body, qs);
			assertTickerAddOrUpdateSucceeded(this, i, response);
			const { includeEnhancedOutput, rawResponse, responseJson } =
				resolveWidgetMapTickerEnhancedOutput(this, i, response);

			const executionData = this.helpers.constructExecutionMetaData(
				[
					{
						json: includeEnhancedOutput
							? {
									success: true,
									resource: 'widgetMapTicker',
									operation: 'addOrUpdateTicker',
									...(sanitizedWidgetId ? { widget_id: sanitizedWidgetId } : {}),
									map_id: sanitizedMapId,
									ticker_ids: tickerIds,
									data: responseJson,
								}
							: rawResponse,
					},
				],
				{ itemData: { item: i } },
			);
			returnData.push(...executionData);
		} catch (error) {
			if (
				pushWidgetMapTickerRecoverableError(this, returnData, i, 'addOrUpdateTicker', error, {
					contextFields: {
						...(sanitizedWidgetId ? { widget_id: sanitizedWidgetId } : {}),
						...(sanitizedMapId ? { map_id: sanitizedMapId } : {}),
						...(tickerIds.length > 0 ? { ticker_ids: tickerIds } : {}),
						...(requestedAppKey ? { appkey: requestedAppKey } : {}),
					},
				})
			) {
				continue;
			}
			throw error;
		}
	}

	return returnData;
}
