export const GITHUB_REPO_BASE_URL = 'https://github.com/phil-fetchski/n8n-nodes-zoho-cliq';

export const AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL = `${GITHUB_REPO_BASE_URL}/blob/main/AiAgentToolDescriptions/Resources`;
export const CREDENTIALS_SETUP_GUIDE_LINK = `${GITHUB_REPO_BASE_URL}/blob/main/documentation/CREDENTIALS.md`;

export const BOT_GET_SUBSCRIBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Bot/get-subscribers.md`;
export const BOT_TRIGGER_BOT_CALL_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Bot/trigger-calls.md`;
export const BULK_ACTION_EXPORT_CHANNELS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/BulkAction/export-channels.md`;
export const BULK_ACTION_EXPORT_CONVERSATION_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/BulkAction/export-conversation-members.md`;
export const BULK_ACTION_EXPORT_CONVERSATIONS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/BulkAction/export-conversations.md`;
export const BULK_ACTION_EXPORT_MESSAGES_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/BulkAction/export-messages.md`;
export const CALLS_MEETING_GET_RECORDING_DETAILS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CallsMeeting/get-recording-details.md`;
export const CALLS_MEETING_LIST_CALL_RECORDINGS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CallsMeeting/list-call-recordings.md`;
export const CHAT_GET_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/get-members.md`;
export const CHAT_GET_PINNED_STICKY_MESSAGE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/get-pinned-sticky-message.md`;
export const CHAT_LEAVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/leave.md`;
export const CHAT_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/list.md`;
export const CHAT_MUTE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/mute.md`;
export const CHAT_PIN_STICKY_MESSAGE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/pin-sticky-message.md`;
export const CHAT_UNMUTE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/unmute.md`;
export const CHAT_UNPIN_STICKY_MESSAGE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Chat/unpin-sticky-message.md`;
export const CHANNEL_ADD_BOT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/add-bot.md`;
export const CHANNEL_ADD_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/add-members.md`;
export const CHANNEL_APPROVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/approve.md`;
export const CHANNEL_ARCHIVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/archive.md`;
export const CHANNEL_CHANGE_PERMISSION_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/change-permission.md`;
export const CHANNEL_CHANGE_ROLE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/change-role.md`;
export const CHANNEL_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/create.md`;
export const CHANNEL_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/delete.md`;
export const CHANNEL_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/get.md`;
export const CHANNEL_GET_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/get-members.md`;
export const CHANNEL_JOIN_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/join.md`;
export const CHANNEL_LEAVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/leave.md`;
export const CHANNEL_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/list.md`;
export const CHANNEL_REJECT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/reject.md`;
export const CHANNEL_REMOVE_BOT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/remove-bot.md`;
export const CHANNEL_REMOVE_MEMBER_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/remove-member.md`;
export const CHANNEL_REMOVE_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/remove-members.md`;
export const CHANNEL_UNARCHIVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/unarchive.md`;
export const CHANNEL_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Channel/update.md`;
export const CUSTOM_DOMAIN_ADD_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomDomain/add.md`;
export const CUSTOM_DOMAIN_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomDomain/delete.md`;
export const CUSTOM_DOMAIN_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomDomain/get.md`;
export const CUSTOM_DOMAIN_VERIFY_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomDomain/verify.md`;
export const CUSTOM_EMAIL_UPDATE_MAIL_CONFIGURATION_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomEmail/update-mail-configuration.md`;
export const CUSTOM_EMAIL_VERIFY_CUSTOM_EMAIL_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/CustomEmail/verify-custom-email.md`;
export const DATABASE_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Database/create.md`;
export const DATABASE_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Database/delete.md`;
export const DATABASE_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Database/get.md`;
export const DATABASE_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Database/list.md`;
export const DATABASE_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Database/update.md`;
export const DEPARTMENT_ADD_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/add-members.md`;
export const DEPARTMENT_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/create.md`;
export const DEPARTMENT_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/delete.md`;
export const DEPARTMENT_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/get.md`;
export const DEPARTMENT_GET_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/get-members.md`;
export const DEPARTMENT_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/list.md`;
export const DEPARTMENT_REMOVE_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/remove-members.md`;
export const DEPARTMENT_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Department/update.md`;
export const DESIGNATION_ADD_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/add-members.md`;
export const DESIGNATION_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/create.md`;
export const DESIGNATION_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/delete.md`;
export const DESIGNATION_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/get.md`;
export const DESIGNATION_GET_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/get-members.md`;
export const DESIGNATION_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/list.md`;
export const DESIGNATION_REMOVE_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/remove-members.md`;
export const DESIGNATION_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Designation/update.md`;
export const EVENTS_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/create.md`;
export const EVENTS_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/delete.md`;
export const EVENTS_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/get.md`;
export const EVENTS_GET_CALENDARS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/get-calendars.md`;
export const EVENTS_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/list.md`;
export const EVENTS_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/update.md`;
export const EVENTS_UPDATE_STATUS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/update-status.md`;
export const EVENTS_UPLOAD_ATTACHMENT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Events/upload-attachment.md`;
export const FILES_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Files/get-file.md`;
export const FILES_SHARE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Files/share-files.md`;
export const MESSAGE_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/delete.md`;
export const MESSAGE_EDIT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/edit.md`;
export const MESSAGE_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/get.md`;
export const MESSAGE_POST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/post.md`;
export const MESSAGE_RETRIEVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/retrieve.md`;
export const MESSAGE_SCHEDULE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Message/schedule-message.md`;
export const MESSAGE_COMPONENT_BUILDER_AGENT_CARD_PAYLOAD_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/MessageComponentBuilder/agent-card-payload-builder.md`;
export const OAUTH_HELPER_CHECK_SCOPE_PACK_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/OAuthHelper/check-scope-pack.md`;
export const OAUTH_HELPER_GET_GRANTED_SCOPES_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/OAuthHelper/get-granted-scopes.md`;
export const OAUTH_HELPER_LIST_SCOPE_PACKS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/OAuthHelper/list-scope-packs.md`;
export const REACTION_ADD_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reaction/add.md`;
export const REACTION_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reaction/get.md`;
export const REACTION_REMOVE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reaction/remove.md`;
export const ROLE_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/create.md`;
export const ROLE_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/delete.md`;
export const ROLE_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/get.md`;
export const ROLE_GET_PERMISSIONS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/get-permissions.md`;
export const ROLE_GET_USERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/get-users.md`;
export const ROLE_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/list.md`;
export const ROLE_ADD_USERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/add-users.md`;
export const ROLE_REMOVE_USERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/remove-users.md`;
export const ROLE_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/update.md`;
export const ROLE_UPDATE_PERMISSIONS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Role/update-permissions.md`;
export const TEAM_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/create.md`;
export const TEAM_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/delete.md`;
export const TEAM_ADD_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/add-members.md`;
export const TEAM_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/get.md`;
export const TEAM_GET_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/get-members.md`;
export const TEAM_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/list.md`;
export const TEAM_REMOVE_MEMBERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/remove-members.md`;
export const TEAM_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Team/update.md`;
export const THREAD_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/create.md`;
export const THREAD_ADD_FOLLOWERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/add-followers.md`;
export const THREAD_AUTO_FOLLOW_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/auto-follow.md`;
export const THREAD_FOLLOW_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/follow.md`;
export const THREAD_GET_FOLLOWERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/get-followers.md`;
export const THREAD_GET_MAIN_MESSAGE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/get-main-message.md`;
export const THREAD_GET_NON_FOLLOWERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/get-non-followers.md`;
export const THREAD_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/list.md`;
export const THREAD_POST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/post.md`;
export const THREAD_REMOVE_FOLLOWERS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/remove-followers.md`;
export const THREAD_SCHEDULE_MESSAGE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/schedule-message.md`;
export const THREAD_UNFOLLOW_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/unfollow.md`;
export const THREAD_UPDATE_STATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Thread/update-state.md`;
export const REMINDERS_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/create.md`;
export const REMINDERS_CLEAR_COMPLETED_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/clear-completed.md`;
export const REMINDERS_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/delete.md`;
export const REMINDERS_DELETE_BATCH_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/delete-batch.md`;
export const REMINDERS_DISMISS_SNOOZE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/dismiss-snooze.md`;
export const REMINDERS_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/get.md`;
export const REMINDERS_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/list.md`;
export const REMINDERS_MARK_COMPLETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/mark-complete.md`;
export const REMINDERS_MARK_INCOMPLETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/mark-incomplete.md`;
export const REMINDERS_ASSIGN_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/assign.md`;
export const REMINDERS_REMOVE_ASSIGNEES_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/remove-assignees.md`;
export const REMINDERS_REMIND_ASSIGNEE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/remind-assignee.md`;
export const REMINDERS_REMIND_ASSIGNEES_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/remind-assignees.md`;
export const REMINDERS_SNOOZE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/snooze.md`;
export const REMINDERS_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/Reminders/update.md`;
export const REMOTE_WORK_CHECK_IN_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/RemoteWork/check-in.md`;
export const REMOTE_WORK_CHECK_OUT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/RemoteWork/check-out.md`;
export const REMOTE_WORK_GET_STATUS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/RemoteWork/get-status.md`;
export const USER_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/create.md`;
export const USER_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/get.md`;
export const USER_GET_TEAMS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/get-teams.md`;
export const USER_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/list.md`;
export const USER_LIST_LAYOUTS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/list-layouts.md`;
export const USER_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/User/update.md`;
export const USER_STATUS_GET_CURRENT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/get-current.md`;
export const USER_STATUS_GET_USER_STATUS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/get-user-status.md`;
export const USER_STATUS_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/list.md`;
export const USER_STATUS_SET_CURRENT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/set-current.md`;
export const USER_STATUS_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/create.md`;
export const USER_STATUS_CREATE_TRANSIENT_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/create-transient.md`;
export const USER_STATUS_CLEAR_MY_STATUS_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/clear-my-status.md`;
export const USER_STATUS_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserStatus/delete.md`;
export const USER_FIELDS_CREATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserField/create.md`;
export const USER_FIELDS_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserField/delete.md`;
export const USER_FIELDS_GET_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserField/get.md`;
export const USER_FIELDS_LIST_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserField/list.md`;
export const USER_FIELDS_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/UserField/update.md`;
export const WIDGET_MAP_TICKER_ADD_OR_UPDATE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/WidgetMapTicker/add-or-update-ticker.md`;
export const WIDGET_MAP_TICKER_DELETE_AGENT_DETAILS_LINK = `${AI_AGENT_TOOL_DESCRIPTIONS_BASE_URL}/WidgetMapTicker/delete-ticker.md`;

export const AI_AGENT_TOOL_DOC_LINKS = {
	bot: {
		getSubscribers: BOT_GET_SUBSCRIBERS_AGENT_DETAILS_LINK,
		triggerCalls: BOT_TRIGGER_BOT_CALL_AGENT_DETAILS_LINK,
	},
	bulkAction: {
		exportChannels: BULK_ACTION_EXPORT_CHANNELS_AGENT_DETAILS_LINK,
		exportConversationMembers: BULK_ACTION_EXPORT_CONVERSATION_MEMBERS_AGENT_DETAILS_LINK,
		exportConversations: BULK_ACTION_EXPORT_CONVERSATIONS_AGENT_DETAILS_LINK,
		exportMessages: BULK_ACTION_EXPORT_MESSAGES_AGENT_DETAILS_LINK,
	},
	callsMeeting: {
		getRecordingDetails: CALLS_MEETING_GET_RECORDING_DETAILS_AGENT_DETAILS_LINK,
		listCallRecordings: CALLS_MEETING_LIST_CALL_RECORDINGS_AGENT_DETAILS_LINK,
	},
	chat: {
		getMembers: CHAT_GET_MEMBERS_AGENT_DETAILS_LINK,
		getPinnedStickyMessage: CHAT_GET_PINNED_STICKY_MESSAGE_AGENT_DETAILS_LINK,
		leave: CHAT_LEAVE_AGENT_DETAILS_LINK,
		list: CHAT_LIST_AGENT_DETAILS_LINK,
		mute: CHAT_MUTE_AGENT_DETAILS_LINK,
		pinStickyMessage: CHAT_PIN_STICKY_MESSAGE_AGENT_DETAILS_LINK,
		unmute: CHAT_UNMUTE_AGENT_DETAILS_LINK,
		unpinStickyMessage: CHAT_UNPIN_STICKY_MESSAGE_AGENT_DETAILS_LINK,
	},
	channel: {
		addBot: CHANNEL_ADD_BOT_AGENT_DETAILS_LINK,
		addMembers: CHANNEL_ADD_MEMBERS_AGENT_DETAILS_LINK,
		approve: CHANNEL_APPROVE_AGENT_DETAILS_LINK,
		archive: CHANNEL_ARCHIVE_AGENT_DETAILS_LINK,
		changePermission: CHANNEL_CHANGE_PERMISSION_AGENT_DETAILS_LINK,
		changeRole: CHANNEL_CHANGE_ROLE_AGENT_DETAILS_LINK,
		create: CHANNEL_CREATE_AGENT_DETAILS_LINK,
		delete: CHANNEL_DELETE_AGENT_DETAILS_LINK,
		get: CHANNEL_GET_AGENT_DETAILS_LINK,
		getMembers: CHANNEL_GET_MEMBERS_AGENT_DETAILS_LINK,
		join: CHANNEL_JOIN_AGENT_DETAILS_LINK,
		leave: CHANNEL_LEAVE_AGENT_DETAILS_LINK,
		list: CHANNEL_LIST_AGENT_DETAILS_LINK,
		reject: CHANNEL_REJECT_AGENT_DETAILS_LINK,
		removeBot: CHANNEL_REMOVE_BOT_AGENT_DETAILS_LINK,
		removeMember: CHANNEL_REMOVE_MEMBER_AGENT_DETAILS_LINK,
		removeMembers: CHANNEL_REMOVE_MEMBERS_AGENT_DETAILS_LINK,
		unarchive: CHANNEL_UNARCHIVE_AGENT_DETAILS_LINK,
		update: CHANNEL_UPDATE_AGENT_DETAILS_LINK,
	},
	customDomain: {
		add: CUSTOM_DOMAIN_ADD_AGENT_DETAILS_LINK,
		delete: CUSTOM_DOMAIN_DELETE_AGENT_DETAILS_LINK,
		get: CUSTOM_DOMAIN_GET_AGENT_DETAILS_LINK,
		verify: CUSTOM_DOMAIN_VERIFY_AGENT_DETAILS_LINK,
	},
	customEmail: {
		updateMailConfiguration: CUSTOM_EMAIL_UPDATE_MAIL_CONFIGURATION_AGENT_DETAILS_LINK,
		verifyCustomEmail: CUSTOM_EMAIL_VERIFY_CUSTOM_EMAIL_AGENT_DETAILS_LINK,
	},
	database: {
		create: DATABASE_CREATE_AGENT_DETAILS_LINK,
		delete: DATABASE_DELETE_AGENT_DETAILS_LINK,
		get: DATABASE_GET_AGENT_DETAILS_LINK,
		list: DATABASE_LIST_AGENT_DETAILS_LINK,
		update: DATABASE_UPDATE_AGENT_DETAILS_LINK,
	},
	department: {
		addMembers: DEPARTMENT_ADD_MEMBERS_AGENT_DETAILS_LINK,
		create: DEPARTMENT_CREATE_AGENT_DETAILS_LINK,
		delete: DEPARTMENT_DELETE_AGENT_DETAILS_LINK,
		get: DEPARTMENT_GET_AGENT_DETAILS_LINK,
		getMembers: DEPARTMENT_GET_MEMBERS_AGENT_DETAILS_LINK,
		list: DEPARTMENT_LIST_AGENT_DETAILS_LINK,
		removeMembers: DEPARTMENT_REMOVE_MEMBERS_AGENT_DETAILS_LINK,
		update: DEPARTMENT_UPDATE_AGENT_DETAILS_LINK,
	},
	designation: {
		addMembers: DESIGNATION_ADD_MEMBERS_AGENT_DETAILS_LINK,
		create: DESIGNATION_CREATE_AGENT_DETAILS_LINK,
		delete: DESIGNATION_DELETE_AGENT_DETAILS_LINK,
		get: DESIGNATION_GET_AGENT_DETAILS_LINK,
		getMembers: DESIGNATION_GET_MEMBERS_AGENT_DETAILS_LINK,
		list: DESIGNATION_LIST_AGENT_DETAILS_LINK,
		removeMembers: DESIGNATION_REMOVE_MEMBERS_AGENT_DETAILS_LINK,
		update: DESIGNATION_UPDATE_AGENT_DETAILS_LINK,
	},
	events: {
		create: EVENTS_CREATE_AGENT_DETAILS_LINK,
		delete: EVENTS_DELETE_AGENT_DETAILS_LINK,
		get: EVENTS_GET_AGENT_DETAILS_LINK,
		getCalendars: EVENTS_GET_CALENDARS_AGENT_DETAILS_LINK,
		list: EVENTS_LIST_AGENT_DETAILS_LINK,
		update: EVENTS_UPDATE_AGENT_DETAILS_LINK,
		updateStatus: EVENTS_UPDATE_STATUS_AGENT_DETAILS_LINK,
		uploadAttachment: EVENTS_UPLOAD_ATTACHMENT_AGENT_DETAILS_LINK,
	},
	files: {
		getFile: FILES_GET_AGENT_DETAILS_LINK,
		shareFile: FILES_SHARE_AGENT_DETAILS_LINK,
	},
	message: {
		delete: MESSAGE_DELETE_AGENT_DETAILS_LINK,
		edit: MESSAGE_EDIT_AGENT_DETAILS_LINK,
		get: MESSAGE_GET_AGENT_DETAILS_LINK,
		post: MESSAGE_POST_AGENT_DETAILS_LINK,
		retrieve: MESSAGE_RETRIEVE_AGENT_DETAILS_LINK,
		scheduleMessage: MESSAGE_SCHEDULE_AGENT_DETAILS_LINK,
	},
	messageComponentBuilder: {
		buildAgentCardPayload: MESSAGE_COMPONENT_BUILDER_AGENT_CARD_PAYLOAD_AGENT_DETAILS_LINK,
	},
	oauthHelper: {
		checkScopePack: OAUTH_HELPER_CHECK_SCOPE_PACK_AGENT_DETAILS_LINK,
		getGrantedScopes: OAUTH_HELPER_GET_GRANTED_SCOPES_AGENT_DETAILS_LINK,
		listScopePacks: OAUTH_HELPER_LIST_SCOPE_PACKS_AGENT_DETAILS_LINK,
	},
	reaction: {
		add: REACTION_ADD_AGENT_DETAILS_LINK,
		get: REACTION_GET_AGENT_DETAILS_LINK,
		remove: REACTION_REMOVE_AGENT_DETAILS_LINK,
	},
	role: {
		addUsers: ROLE_ADD_USERS_AGENT_DETAILS_LINK,
		create: ROLE_CREATE_AGENT_DETAILS_LINK,
		delete: ROLE_DELETE_AGENT_DETAILS_LINK,
		get: ROLE_GET_AGENT_DETAILS_LINK,
		getPermissions: ROLE_GET_PERMISSIONS_AGENT_DETAILS_LINK,
		getUsers: ROLE_GET_USERS_AGENT_DETAILS_LINK,
		list: ROLE_LIST_AGENT_DETAILS_LINK,
		removeUsers: ROLE_REMOVE_USERS_AGENT_DETAILS_LINK,
		update: ROLE_UPDATE_AGENT_DETAILS_LINK,
		updatePermissions: ROLE_UPDATE_PERMISSIONS_AGENT_DETAILS_LINK,
	},
	team: {
		addMembers: TEAM_ADD_MEMBERS_AGENT_DETAILS_LINK,
		create: TEAM_CREATE_AGENT_DETAILS_LINK,
		delete: TEAM_DELETE_AGENT_DETAILS_LINK,
		get: TEAM_GET_AGENT_DETAILS_LINK,
		getMembers: TEAM_GET_MEMBERS_AGENT_DETAILS_LINK,
		list: TEAM_LIST_AGENT_DETAILS_LINK,
		removeMembers: TEAM_REMOVE_MEMBERS_AGENT_DETAILS_LINK,
		update: TEAM_UPDATE_AGENT_DETAILS_LINK,
	},
	thread: {
		addFollowers: THREAD_ADD_FOLLOWERS_AGENT_DETAILS_LINK,
		autoFollow: THREAD_AUTO_FOLLOW_AGENT_DETAILS_LINK,
		create: THREAD_CREATE_AGENT_DETAILS_LINK,
		follow: THREAD_FOLLOW_AGENT_DETAILS_LINK,
		getFollowers: THREAD_GET_FOLLOWERS_AGENT_DETAILS_LINK,
		getMainMessage: THREAD_GET_MAIN_MESSAGE_AGENT_DETAILS_LINK,
		getNonFollowers: THREAD_GET_NON_FOLLOWERS_AGENT_DETAILS_LINK,
		list: THREAD_LIST_AGENT_DETAILS_LINK,
		post: THREAD_POST_AGENT_DETAILS_LINK,
		removeFollowers: THREAD_REMOVE_FOLLOWERS_AGENT_DETAILS_LINK,
		scheduleMessage: THREAD_SCHEDULE_MESSAGE_AGENT_DETAILS_LINK,
		unfollow: THREAD_UNFOLLOW_AGENT_DETAILS_LINK,
		updateState: THREAD_UPDATE_STATE_AGENT_DETAILS_LINK,
	},
	reminders: {
		assign: REMINDERS_ASSIGN_AGENT_DETAILS_LINK,
		clearCompleted: REMINDERS_CLEAR_COMPLETED_AGENT_DETAILS_LINK,
		create: REMINDERS_CREATE_AGENT_DETAILS_LINK,
		delete: REMINDERS_DELETE_AGENT_DETAILS_LINK,
		deleteBatch: REMINDERS_DELETE_BATCH_AGENT_DETAILS_LINK,
		dismissSnooze: REMINDERS_DISMISS_SNOOZE_AGENT_DETAILS_LINK,
		get: REMINDERS_GET_AGENT_DETAILS_LINK,
		list: REMINDERS_LIST_AGENT_DETAILS_LINK,
		markComplete: REMINDERS_MARK_COMPLETE_AGENT_DETAILS_LINK,
		markIncomplete: REMINDERS_MARK_INCOMPLETE_AGENT_DETAILS_LINK,
		remindAssignee: REMINDERS_REMIND_ASSIGNEE_AGENT_DETAILS_LINK,
		remindAssignees: REMINDERS_REMIND_ASSIGNEES_AGENT_DETAILS_LINK,
		removeAssignees: REMINDERS_REMOVE_ASSIGNEES_AGENT_DETAILS_LINK,
		snooze: REMINDERS_SNOOZE_AGENT_DETAILS_LINK,
		update: REMINDERS_UPDATE_AGENT_DETAILS_LINK,
	},
	remoteWork: {
		checkIn: REMOTE_WORK_CHECK_IN_AGENT_DETAILS_LINK,
		checkOut: REMOTE_WORK_CHECK_OUT_AGENT_DETAILS_LINK,
		getStatus: REMOTE_WORK_GET_STATUS_AGENT_DETAILS_LINK,
	},
	user: {
		create: USER_CREATE_AGENT_DETAILS_LINK,
		get: USER_GET_AGENT_DETAILS_LINK,
		getTeams: USER_GET_TEAMS_AGENT_DETAILS_LINK,
		list: USER_LIST_AGENT_DETAILS_LINK,
		listLayouts: USER_LIST_LAYOUTS_AGENT_DETAILS_LINK,
		update: USER_UPDATE_AGENT_DETAILS_LINK,
	},
	userStatus: {
		clearMyStatus: USER_STATUS_CLEAR_MY_STATUS_AGENT_DETAILS_LINK,
		create: USER_STATUS_CREATE_AGENT_DETAILS_LINK,
		createTransient: USER_STATUS_CREATE_TRANSIENT_AGENT_DETAILS_LINK,
		delete: USER_STATUS_DELETE_AGENT_DETAILS_LINK,
		getCurrent: USER_STATUS_GET_CURRENT_AGENT_DETAILS_LINK,
		getUserStatus: USER_STATUS_GET_USER_STATUS_AGENT_DETAILS_LINK,
		list: USER_STATUS_LIST_AGENT_DETAILS_LINK,
		setCurrent: USER_STATUS_SET_CURRENT_AGENT_DETAILS_LINK,
	},
	userFields: {
		create: USER_FIELDS_CREATE_AGENT_DETAILS_LINK,
		delete: USER_FIELDS_DELETE_AGENT_DETAILS_LINK,
		get: USER_FIELDS_GET_AGENT_DETAILS_LINK,
		list: USER_FIELDS_LIST_AGENT_DETAILS_LINK,
		update: USER_FIELDS_UPDATE_AGENT_DETAILS_LINK,
	},
	widgetMapTicker: {
		addOrUpdateTicker: WIDGET_MAP_TICKER_ADD_OR_UPDATE_AGENT_DETAILS_LINK,
		deleteTicker: WIDGET_MAP_TICKER_DELETE_AGENT_DETAILS_LINK,
	},
} as const;
