import {
	AI_AGENT_TOOL_DOC_LINKS,
	REMINDERS_ASSIGN_AGENT_DETAILS_LINK,
	REMINDERS_CLEAR_COMPLETED_AGENT_DETAILS_LINK,
	REMINDERS_CREATE_AGENT_DETAILS_LINK,
	REMINDERS_DELETE_AGENT_DETAILS_LINK,
	REMINDERS_DELETE_BATCH_AGENT_DETAILS_LINK,
	REMINDERS_DISMISS_SNOOZE_AGENT_DETAILS_LINK,
	REMINDERS_GET_AGENT_DETAILS_LINK,
	REMINDERS_LIST_AGENT_DETAILS_LINK,
	REMINDERS_MARK_COMPLETE_AGENT_DETAILS_LINK,
	REMINDERS_MARK_INCOMPLETE_AGENT_DETAILS_LINK,
	REMINDERS_REMIND_ASSIGNEE_AGENT_DETAILS_LINK,
	REMINDERS_REMIND_ASSIGNEES_AGENT_DETAILS_LINK,
	REMINDERS_REMOVE_ASSIGNEES_AGENT_DETAILS_LINK,
	REMINDERS_SNOOZE_AGENT_DETAILS_LINK,
	REMINDERS_UPDATE_AGENT_DETAILS_LINK,
} from '../../../../../nodes/ZohoCliq/v1/helpers/linkConstants';

describe('ZohoCliq - linkConstants reminders links', () => {
	it('should expose Reminders AI guide links directly and through the grouped registry', () => {
		expect(REMINDERS_ASSIGN_AGENT_DETAILS_LINK).toContain('/Reminders/assign.md');
		expect(REMINDERS_CLEAR_COMPLETED_AGENT_DETAILS_LINK).toContain('/Reminders/clear-completed.md');
		expect(REMINDERS_CREATE_AGENT_DETAILS_LINK).toContain('/Reminders/create.md');
		expect(REMINDERS_DELETE_AGENT_DETAILS_LINK).toContain('/Reminders/delete.md');
		expect(REMINDERS_DELETE_BATCH_AGENT_DETAILS_LINK).toContain('/Reminders/delete-batch.md');
		expect(REMINDERS_DISMISS_SNOOZE_AGENT_DETAILS_LINK).toContain('/Reminders/dismiss-snooze.md');
		expect(REMINDERS_GET_AGENT_DETAILS_LINK).toContain('/Reminders/get.md');
		expect(REMINDERS_LIST_AGENT_DETAILS_LINK).toContain('/Reminders/list.md');
		expect(REMINDERS_MARK_COMPLETE_AGENT_DETAILS_LINK).toContain('/Reminders/mark-complete.md');
		expect(REMINDERS_MARK_INCOMPLETE_AGENT_DETAILS_LINK).toContain('/Reminders/mark-incomplete.md');
		expect(REMINDERS_REMIND_ASSIGNEE_AGENT_DETAILS_LINK).toContain('/Reminders/remind-assignee.md');
		expect(REMINDERS_REMIND_ASSIGNEES_AGENT_DETAILS_LINK).toContain(
			'/Reminders/remind-assignees.md',
		);
		expect(REMINDERS_REMOVE_ASSIGNEES_AGENT_DETAILS_LINK).toContain(
			'/Reminders/remove-assignees.md',
		);
		expect(REMINDERS_SNOOZE_AGENT_DETAILS_LINK).toContain('/Reminders/snooze.md');
		expect(REMINDERS_UPDATE_AGENT_DETAILS_LINK).toContain('/Reminders/update.md');

		expect(AI_AGENT_TOOL_DOC_LINKS.reminders).toEqual({
			assign: REMINDERS_ASSIGN_AGENT_DETAILS_LINK,
			clearCompleted: REMINDERS_CLEAR_COMPLETED_AGENT_DETAILS_LINK,
			create: REMINDERS_CREATE_AGENT_DETAILS_LINK,
			delete: REMINDERS_DELETE_AGENT_DETAILS_LINK,
			deleteBatch: REMINDERS_DELETE_BATCH_AGENT_DETAILS_LINK,
			dismissSnooze: REMINDERS_DISMISS_SNOOZE_AGENT_DETAILS_LINK,
			get: REMINDERS_GET_AGENT_DETAILS_LINK,
			list: REMINDERS_LIST_AGENT_DETAILS_LINK,
			markComplete: REMINDERS_MARK_COMPLETE_AGENT_DETAILS_LINK,
			markIncomplete: REMINDERS_MARK_INCOMPLETE_AGENT_DETAILS_LINK,
			remindAssignee: REMINDERS_REMIND_ASSIGNEE_AGENT_DETAILS_LINK,
			remindAssignees: REMINDERS_REMIND_ASSIGNEES_AGENT_DETAILS_LINK,
			removeAssignees: REMINDERS_REMOVE_ASSIGNEES_AGENT_DETAILS_LINK,
			snooze: REMINDERS_SNOOZE_AGENT_DETAILS_LINK,
			update: REMINDERS_UPDATE_AGENT_DETAILS_LINK,
		});
	});
});
